spring.application.name=project-manager
server.port=${PORT:8080}

# Use individual MySQL variables
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:project_manager}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

app.jwt.secret=${JWT_SECRET:ProjectManagerJwtSecretKey2026ForSpringBootSecurityDemo12345}
app.jwt.expiration-minutes=1440
app.cors.allowed-origin=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://https://project-manager-app-inky.vercel.app/}